const partograph = {
  id: 'partograph',
  name: 'Labour Progress Assessment',
  shortName: 'Labour Monitoring',
  categoryId: 'obgyn',
  description: 'Structured labour monitoring snapshot informed by the WHO Labour Care Guide approach.',
  type: 'calculation',

  inputs: [
    {
      id: 'dilation',
      label: 'Cervical dilation',
      type: 'number',
      unit: 'cm',
      min: 0,
      max: 10,
      step: 0.1
    },
    {
      id: 'hours',
      label: 'Hours since active labour assessment began',
      type: 'number',
      unit: 'hours',
      min: 0,
      step: 0.1
    },
    {
      id: 'fhr',
      label: 'Fetal heart rate',
      type: 'number',
      unit: 'bpm',
      min: 50,
      max: 250
    },
    {
      id: 'contractions',
      label: 'Contractions per 10 minutes',
      type: 'number',
      min: 0,
      max: 10,
      step: 1
    },
    {
      id: 'pulse',
      label: 'Maternal pulse',
      type: 'number',
      unit: 'bpm',
      min: 30,
      max: 220
    },
    {
      id: 'systolic',
      label: 'Maternal systolic BP',
      type: 'number',
      unit: 'mmHg',
      min: 50,
      max: 250
    },
    {
      id: 'diastolic',
      label: 'Maternal diastolic BP',
      type: 'number',
      unit: 'mmHg',
      min: 20,
      max: 150
    },
    {
      id: 'temperature',
      label: 'Maternal temperature',
      type: 'number',
      unit: 'C',
      min: 30,
      max: 45,
      step: 0.1
    }
  ],

  calculate(v) {
    const dilation = Number(v.dilation);
    const hours = Number(v.hours);
    const fhr = Number(v.fhr);
    const contractions = Number(v.contractions);
    const pulse = Number(v.pulse);
    const systolic = Number(v.systolic);
    const diastolic = Number(v.diastolic);
    const temperature = Number(v.temperature);

    if (
      !Number.isFinite(dilation) ||
      !Number.isFinite(hours) ||
      !Number.isFinite(fhr) ||
      !Number.isFinite(contractions) ||
      !Number.isFinite(pulse) ||
      !Number.isFinite(systolic) ||
      !Number.isFinite(diastolic) ||
      !Number.isFinite(temperature)
    ) {
      return {
        error: 'Enter valid values for the labour assessment.'
      };
    }

    const alerts = [];

    if (dilation < 5) {
      alerts.push('Cervical dilation is below the WHO active first-stage threshold of 5 cm.');
    }

    if (fhr < 110 || fhr > 160) {
      alerts.push('Fetal heart rate is outside the usual 110-160 bpm reference range.');
    }

    if (contractions >= 5) {
      alerts.push('Five or more contractions in 10 minutes.');
    }

    if (systolic >= 140 || diastolic >= 90) {
      alerts.push('Maternal blood pressure is elevated.');
    }

    if (systolic >= 160 || diastolic >= 110) {
      alerts.push('Severe-range maternal blood pressure.');
    }

    if (temperature >= 38) {
      alerts.push('Maternal temperature is >=38 C.');
    }

    if (pulse >= 120) {
      alerts.push('Maternal pulse is elevated.');
    }

    return {
      value: dilation,
      displayValue: `${dilation.toFixed(1)} cm`,
      unit: 'cervical dilation',
      interpretation: alerts.length
        ? `${alerts.length} monitoring flag${alerts.length > 1 ? 's' : ''}`
        : 'No flag generated by the entered observations',
      note: alerts.length
        ? alerts.join(' ')
        : 'This is a structured monitoring snapshot, not a substitute for the full WHO Labour Care Guide or continuous clinical assessment. WHO no longer recommends using a universal 1 cm/hour cervical dilation rule as an intervention trigger.'
    };
  }
};

export default partograph;
